# Entity type and additional information

uint8 category              # Major category for the entity. Extra entity type distinction can be made through tags.
                            # See EntityCategories for defined category values.
string description          # optional: verbose, human-readable description of the entity.
string[] tags               # optional: tags which are useful for filtering and categorizing entities further.
