# Remove an entity (a robot, other object) by unique name from the simulation

string name                         # Unique name with a namespace, as returned by SpawnEntity or GetEntities.

---

Result result
