# Return a list of available world resources which are valid as LoadWorld uri fields
#
# Support for this interface is indicated through the AVAILABLE_WORLDS value in GetSimulatorFeatures.

# Optional field for additional sources (local or remote) to search
string[] sources
---
# Standard result message
simulation_interfaces/Result result

# Available world resources with URI and additional information
simulation_interfaces/WorldResource[] worlds 
