# Get geometrical bounds for entity. This feature is available if GetSimulatorFeatures includes ENTITY_BOUNDS feature.

Entity entity                         # Entity identified by its unique name as returned by GetEntities / SpawnEntity.

---

Result result
Bounds bounds                         # Entity bounds. Only valid if result.result_code is OK.
