# Get objects in the scene which can be interacted, e.g. with using SetEntityState.

string filter                                       # Optional, defaults to empty. Return entities with matching names.
                                                    # Entity names are matched with the filter regular expression.
                                                    # An empty filter will result in all entities being returned.
                                                    # Applies together with other filters (categories, tags).
uint8[] categories                                  # Optional, defaults to empty, which means no category filter.
                                                    # Entities matching any of the categories will be returned.
                                                    # To get entity category, use GetEntityInfo.
                                                    # Applies together with other filters (filter, tags).
string[] tags                                       # Optional, defaults to empty, which means no tags filter.
                                                    # Entities matching any or all of tags will be returned, depending
                                                    # on tags_filter_mode. To get entity tags, use GetEntityInfo.
                                                    # Applies together with other filters (filter, categories).

uint8 ANY_OF    = 0                                 # Filter with AND mode (all tags need to match).
uint8 ALL_OF    = 1                                 # Filter with OR mode (any tag can match).

uint8 tags_filter_mode                              # Set to control filter application for tags.


---

Result result
EntityWithState[] entities                          # All entities with their states, matching the filter.
