# Get type and other information about an entity.

string name                           # Unique name as returned by GetEntities / SpawnEntity.

---

Result result
EntityInfo info                       # Only valid if result.result_code is OK.
