# Get state of an entity.

string name                                             # Unique name as returned by GetEntities / SpawnEntity.

---

Result result
EntityState state                                       # Entity ground truth state. Valid when result.result = OK.
