# Get state of an entity.

string name                                             # Unique name as returned by GetEntities / SpawnEntity.

---

EntityState entity_state                                # Entity ground truth state.

bool success                                            # Return true if successful.
string status_message                                   # Additional comments or error status.
