# Get state of an entity.

string entity                         # Entity identified by its unique name as returned by GetEntities / SpawnEntity.

---

Result result
EntityState state                     # Entity ground truth state. Valid when result.result = OK.
