# Pauses or unpauses the simulation

bool pause                          # If true, sets simulation state to paused, otherwise sets it to running.
                                    # If already in target state, nothing happens but the result informs about it.

---

uint8 ALREADY_PAUSED = 101          # Additional result type for this call, which means simulation was already
                                    # paused and remains so.

Result result