# Spawn an entity (a robot, other object) by name or URI

string name                             # A name to give to the spawned entity.
                                        # If empty, a name field in the uri file or resource_string will be used,
                                        # if supported and not empty (e.g. "name" field in SDFormat, URDF).
                                        # If the name is still empty or not unique (as determined by the simulator),
                                        # the service returns a generated name in the entity_name response field if the
                                        # allow_renaming field is set to true. Otherwise, the service call fails and an
                                        # error is returned in the status_message.
bool allow_renaming                     # Determines whether the spawning succeeds with a non-unique name.
                                        # If it is set to true, the user should always check entity_name response field
                                        # and use it for any further interactions.
string uri                              # Resource such as SDFormat, URDF, USD or MJCF file, a native prefab, etc.
                                        # Valid URIs can be determined by calling GetSpawnables first, and you can check
                                        # the simulator format support by reading SimulatorFeatures spawn_formats field.
                                        # If uri field is empty, resource_string must not be empty.
string resource_string                  # An entity definition file passed as a string.
                                        # Simulators may support spawning from a file generated on the fly (e.g. XACRO).
                                        # Check whether it is supported by your simulator through GetSimulatorFeatures.
                                        # If uri field is not empty, resource_string field will be ignored.
string entity_namespace                 # Spawn the entity with all its interfaces under this namespace.
geometry_msgs/PoseStamped initial_pose  # Initial entity pose.
                                        # The header contains a reference frame, which defaults to global "world" frame.
                                        # This frame must be known to the simulator, e.g. of an object spawned earlier.
                                        # The timestamp field in the header is ignored.

---

bool success                        # Return true if spawned successfully.
string status_message               # On failure, a user-friendly error message.
string entity_name                  # Spawned entity full name, guaranteed to be unique in the simulation.
                                    # If allow_renaming is true, it may differ from the request name field.
