# Assuming the simulation is paused, simulate a finite number of steps and return to paused state.
# The service only returns once stepping is complete, which might take considerable time.
# There is an alternative in MultiStepSimulation action, which is worth considering for a multi-step interface.

uint16 steps                        # Step through the simulation loop this many times.

---

bool success                        # Return true if stepping is supported and was successful.
string status_message               # Additional comments or error status.
                                    # Calling with simulation not paused will return failure and an appropriate message.
