# Unload the current simulation world
#
# Support for this interface is indicated through the WORLD_UNLOADING value in GetSimulatorFeatures.

# If true, existing dynamically spawned entities will remain
bool keep_entities
---
# Standard result message
simulation_interfaces/Result result 
